# -*- coding: utf-8 -*-

from __future__ import annotations

import unittest
import numpy as np

from asset_asrl.Astro import Constants as constants
from asset_asrl.Astro.Extensions.TwoBodyFrame import TwoBodyFrame


# ============================================================================
# Basic characteristic-scale tests
# ============================================================================

class TwoBodyFrameCharacteristicScaleTests(unittest.TestCase):
    """Verify the fundamental characteristic quantities generated by TwoBodyFrame."""

    def test_earth_surface_scales_match_keplerian_relations(self):
        """Verify Earth-based characteristic scales satisfy Keplerian identities."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertEqual(frame.mu, 1)
        self.assertAlmostEqual(frame.tstar, np.sqrt(frame.lstar**3 / frame.P1mu))
        self.assertAlmostEqual(frame.vstar, np.sqrt(frame.P1mu / frame.lstar))
        self.assertAlmostEqual(frame.astar, frame.vstar / frame.tstar)
        self.assertAlmostEqual(frame.astar, frame.P1mu / frame.lstar**2)
        self.assertAlmostEqual(frame.mustar, constants.MuEarth)

    def test_characteristic_units_are_self_consistent(self):
        """Verify characteristic velocity and acceleration follow from length and time scales."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertAlmostEqual(frame.lstar / frame.tstar, frame.vstar)
        self.assertAlmostEqual(frame.lstar / frame.tstar**2, frame.astar)

    def test_characteristic_length_is_preserved(self):
        """Verify the characteristic length is the supplied reference length."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertAlmostEqual(frame.lstar, constants.RadiusEarth)

    def test_characteristic_gravitational_parameter_is_preserved(self):
        """Verify the dimensional gravitational parameter is retained."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertAlmostEqual(frame.mustar, constants.MuEarth)

    def test_velocity_acceleration_time_identity(self):
        """Verify the dimensional identity a* * t* = v*."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertAlmostEqual(frame.astar * frame.tstar, frame.vstar)

    def test_length_acceleration_velocity_identity(self):
        """Verify the dimensional identity v*^2 = a* * l*."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertAlmostEqual(frame.vstar**2, frame.astar * frame.lstar)


# ============================================================================
# Nondimensionalization tests
# ============================================================================

class TwoBodyFrameNondimensionalizationTests(unittest.TestCase):
    """Verify that TwoBodyFrame correctly nondimensionalizes the two-body system."""

    def test_nondimensional_gravitational_parameter_is_unity(self):
        """Verify characteristic scaling normalizes the gravitational parameter to one."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        nondimensional_mu = frame.P1mu * frame.tstar**2 / frame.lstar**3
        self.assertAlmostEqual(nondimensional_mu, 1.0)

    def test_earth_and_sun_frames_both_normalize_mu(self):
        """Verify Earth-centered and Sun-centered frames both normalize mu to one."""
        earth_frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        sun_frame = TwoBodyFrame(constants.MuSun, constants.AU)

        for frame in (earth_frame, sun_frame):
            nondimensional_mu = frame.P1mu * frame.tstar**2 / frame.lstar**3
            self.assertAlmostEqual(nondimensional_mu, 1.0)

    def test_nondimensional_circular_orbit_energy_is_independent_of_mu(self):
        """Verify characteristic scaling produces the same nondimensional circular-orbit energy for different systems."""
        earth_frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        solar_frame = TwoBodyFrame(constants.MuSun, constants.AU)

        for frame in (earth_frame, solar_frame):
            specific_energy = -frame.P1mu / (2.0 * frame.lstar)
            nondimensional_energy = specific_energy / frame.vstar**2
            self.assertAlmostEqual(nondimensional_energy, -0.5)

    def test_circular_orbit_has_unit_nondimensional_speed_and_period(self):
        """Verify a circular orbit at the characteristic radius has unit speed and period 2*pi."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        circular_speed = np.sqrt(constants.MuEarth / constants.RadiusEarth)
        circular_period = 2.0 * np.pi * np.sqrt(constants.RadiusEarth**3 / constants.MuEarth)
        self.assertAlmostEqual(circular_speed / frame.vstar, 1.0)
        self.assertAlmostEqual(circular_period / frame.tstar, 2.0 * np.pi)


# ============================================================================
# Keplerian orbital mechanics tests
# ============================================================================

class TwoBodyFrameKeplerianTests(unittest.TestCase):
    """Verify characteristic scaling against fundamental Keplerian relationships."""

    def test_kepler_third_law(self):
        """Verify Kepler's third law using the characteristic scales."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        period = 2.0 * np.pi * np.sqrt(frame.lstar**3 / frame.P1mu)
        self.assertAlmostEqual(period / frame.tstar, 2.0 * np.pi)

    def test_escape_speed_is_sqrt_two_times_circular_speed(self):
        """Verify the standard two-body escape-speed relationship."""
        circular_speed = np.sqrt(constants.MuEarth / constants.RadiusEarth)
        escape_speed = np.sqrt(2.0 * constants.MuEarth / constants.RadiusEarth)
        self.assertAlmostEqual(escape_speed / circular_speed, np.sqrt(2.0))

    def test_circular_orbit_specific_energy_matches_keplerian_value(self):
        """Verify circular-orbit specific energy matches the Keplerian result."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        radius = constants.RadiusEarth
        circular_speed = np.sqrt(constants.MuEarth / radius)
        specific_energy = 0.5 * circular_speed**2 - constants.MuEarth / radius
        expected_energy = -constants.MuEarth / (2.0 * radius)
        self.assertAlmostEqual(specific_energy, expected_energy)
        nondimensional_energy = specific_energy / frame.vstar**2
        self.assertAlmostEqual(nondimensional_energy, -0.5)

    def test_escape_orbit_has_zero_specific_energy(self):
        """Verify escape velocity produces approximately zero specific energy."""
        radius = constants.RadiusEarth
        escape_speed = np.sqrt(2.0 * constants.MuEarth / radius)
        specific_energy = 0.5 * escape_speed**2 - constants.MuEarth / radius
        self.assertAlmostEqual(specific_energy, 0.0, delta=1.0e-8)

    def test_vis_viva_equation_at_multiple_radii(self):
        """Verify characteristic velocity is consistent with vis-viva at several radii."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        radii = np.array([constants.RadiusEarth, 2.0 * constants.RadiusEarth, 3.0 * constants.RadiusEarth, 5.0 * constants.RadiusEarth])

        for radius in radii:
            circular_speed = np.sqrt(constants.MuEarth / radius)
            semi_major_axis = radius
            vis_viva_speed = np.sqrt(constants.MuEarth * (2.0 / radius - 1.0 / semi_major_axis))
            self.assertAlmostEqual(circular_speed, vis_viva_speed)

        characteristic_speed = np.sqrt(frame.P1mu / frame.lstar)
        self.assertAlmostEqual(characteristic_speed / frame.vstar, 1.0)

    def test_circular_acceleration_matches_gravity(self):
        """Verify characteristic acceleration agrees with gravity at the characteristic radius."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        gravitational_acceleration = constants.MuEarth / constants.RadiusEarth**2
        self.assertAlmostEqual(frame.astar, gravitational_acceleration)


# ============================================================================
# Scaling-law tests
# ============================================================================

class TwoBodyFrameScalingTests(unittest.TestCase):
    """Verify characteristic-scale power laws with respect to length and mu."""

    def test_characteristic_scales_change_consistently_with_length_scale(self):
        """Verify characteristic scales follow the expected power laws with length."""
        frame1 = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        frame2 = TwoBodyFrame(constants.MuEarth, 2.0 * constants.RadiusEarth)
        self.assertAlmostEqual(frame2.tstar / frame1.tstar, 2.0**1.5)
        self.assertAlmostEqual(frame2.vstar / frame1.vstar, 1.0 / np.sqrt(2.0))
        self.assertAlmostEqual(frame2.astar / frame1.astar, 0.25)

    def test_velocity_scale_changes_with_gravitational_parameter(self):
        """Verify the expected square-root dependence of velocity on mu."""
        radius = constants.RadiusEarth
        frame1 = TwoBodyFrame(constants.MuEarth, radius)
        frame2 = TwoBodyFrame(4.0 * constants.MuEarth, radius)
        self.assertAlmostEqual(frame2.vstar / frame1.vstar, 2.0)

    def test_time_scale_changes_with_gravitational_parameter(self):
        """Verify the expected inverse square-root dependence of time on mu."""
        radius = constants.RadiusEarth
        frame1 = TwoBodyFrame(constants.MuEarth, radius)
        frame2 = TwoBodyFrame(4.0 * constants.MuEarth, radius)
        self.assertAlmostEqual(frame2.tstar / frame1.tstar, 0.5)

    def test_acceleration_scale_changes_with_gravitational_parameter(self):
        """Verify acceleration has the expected linear dependence on mu."""
        radius = constants.RadiusEarth
        frame1 = TwoBodyFrame(constants.MuEarth, radius)
        frame2 = TwoBodyFrame(4.0 * constants.MuEarth, radius)
        self.assertAlmostEqual(frame2.astar / frame1.astar, 4.0)

    def test_scaling_invariant_under_simultaneous_length_and_mu_change(self):
        """Verify characteristic scaling adapts correctly when both mu and length change."""
        frame1 = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        frame2 = TwoBodyFrame(4.0 * constants.MuEarth, 4.0 * constants.RadiusEarth)
        self.assertAlmostEqual(frame2.tstar / frame1.tstar, 4.0)
        self.assertAlmostEqual(frame2.vstar / frame1.vstar, 1.0)
        self.assertAlmostEqual(frame2.astar / frame1.astar, 0.25)


# ============================================================================
# Solar-system reference tests
# ============================================================================

class TwoBodyFrameSolarSystemTests(unittest.TestCase):
    """Verify TwoBodyFrame against Earth and Sun reference scales."""

    def test_one_au_solar_orbit_has_about_one_year_period(self):
        """Verify a one-AU solar orbit has approximately a one-year period."""
        frame = TwoBodyFrame(constants.MuSun, constants.AU)
        orbital_period_days = 2.0 * np.pi * frame.tstar / constants.day
        self.assertGreater(orbital_period_days, 365.0)
        self.assertLess(orbital_period_days, 366.0)

    def test_solar_characteristic_velocity_matches_earth_orbital_speed_scale(self):
        """Verify the one-AU solar velocity scale is near Earth's orbital speed."""
        frame = TwoBodyFrame(constants.MuSun, constants.AU)
        earth_orbital_speed_ms = frame.vstar
        self.assertGreater(earth_orbital_speed_ms, 29_000.0)
        self.assertLess(earth_orbital_speed_ms, 31_000.0)
        
        
# ============================================================================
# Additional orbital-energy regression tests
# ============================================================================

class TwoBodyFrameEnergyTests(unittest.TestCase):
    """Verify energy relationships associated with two-body motion."""

    def test_circular_orbit_energy_from_velocity_and_potential(self):
        """Verify circular-orbit kinetic plus potential energy equals -mu/(2r)."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        radius = frame.lstar
        velocity = frame.vstar
        kinetic_energy = 0.5 * velocity**2
        potential_energy = -frame.P1mu / radius
        total_energy = kinetic_energy + potential_energy
        expected_energy = -frame.P1mu / (2.0 * radius)
        self.assertAlmostEqual(total_energy, expected_energy)

    def test_escape_energy_is_zero_in_nondimensional_units(self):
        """Verify escape velocity produces zero nondimensional specific energy."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        escape_velocity = np.sqrt(2.0 * frame.P1mu / frame.lstar)
        energy = 0.5 * escape_velocity**2 - frame.P1mu / frame.lstar
        self.assertLess(abs(energy), 1.0e-8)

    def test_circular_orbit_kinetic_energy_is_half_magnitude_of_potential_energy(self):
        """Verify circular-orbit kinetic energy is half the magnitude of potential energy."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        radius = frame.lstar
        kinetic_energy = 0.5 * frame.vstar**2
        potential_energy = frame.P1mu / radius
        self.assertAlmostEqual(kinetic_energy / potential_energy, 0.5)

    def test_circular_orbit_total_energy_is_negative(self):
        """Verify a circular orbit is a bound orbit with negative specific energy."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        energy = 0.5 * frame.vstar**2 - frame.P1mu / frame.lstar
        self.assertLess(energy, 0.0)

    def test_escape_velocity_is_greater_than_circular_velocity(self):
        """Verify escape velocity exceeds circular velocity."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        circular_velocity = np.sqrt(frame.P1mu / frame.lstar)
        escape_velocity = np.sqrt(2.0 * frame.P1mu / frame.lstar)
        self.assertGreater(escape_velocity, circular_velocity)


# ============================================================================
# Gravitational acceleration regression tests
# ============================================================================

class TwoBodyFrameGravityTests(unittest.TestCase):
    """Verify characteristic acceleration against Newtonian gravity."""

    def test_gravity_at_characteristic_radius(self):
        """Verify gravity at l* equals the characteristic acceleration."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        gravity = frame.P1mu / frame.lstar**2
        self.assertAlmostEqual(gravity, frame.astar)

    def test_gravity_scales_inverse_square_with_radius(self):
        """Verify Newtonian gravitational acceleration follows the inverse-square law."""
        mu = constants.MuEarth
        radius1 = constants.RadiusEarth
        radius2 = 2.0 * radius1
        gravity1 = mu / radius1**2
        gravity2 = mu / radius2**2
        self.assertAlmostEqual(gravity2 / gravity1, 0.25)

    def test_gravity_scales_inverse_square_over_multiple_radii(self):
        """Verify inverse-square gravity scaling over several radii."""
        mu = constants.MuEarth
        radius = constants.RadiusEarth
        reference_gravity = mu / radius**2

        for multiplier in (1.0, 2.0, 3.0, 5.0, 10.0):
            test_radius = multiplier * radius
            gravity = mu / test_radius**2
            expected_ratio = 1.0 / multiplier**2
            self.assertAlmostEqual(gravity / reference_gravity, expected_ratio)

    def test_gravity_and_velocity_scale_are_related(self):
        """Verify v*^2/l* equals the characteristic gravitational acceleration."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertAlmostEqual(frame.vstar**2 / frame.lstar, frame.astar)

    def test_gravity_and_time_scale_are_related(self):
        """Verify l*/t*^2 equals the characteristic gravitational acceleration."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertAlmostEqual(frame.lstar / frame.tstar**2, frame.astar)


# ============================================================================
# Orbital-period regression tests
# ============================================================================

class TwoBodyFrameOrbitalPeriodTests(unittest.TestCase):
    """Verify orbital-period relationships from Keplerian dynamics."""

    def test_characteristic_period_is_two_pi_time_units(self):
        """Verify the characteristic circular-orbit period is 2*pi."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        period = 2.0 * np.pi * frame.tstar
        self.assertAlmostEqual(period / frame.tstar, 2.0 * np.pi)

    def test_period_scales_with_radius_to_three_halves(self):
        """Verify orbital period scales as radius^(3/2) for fixed mu."""
        mu = constants.MuEarth
        radius1 = constants.RadiusEarth
        radius2 = 2.0 * radius1
        period1 = 2.0 * np.pi * np.sqrt(radius1**3 / mu)
        period2 = 2.0 * np.pi * np.sqrt(radius2**3 / mu)
        self.assertAlmostEqual(period2 / period1, 2.0**1.5)

    def test_period_scales_with_inverse_square_root_mu(self):
        """Verify orbital period scales as mu^(-1/2) for fixed radius."""
        radius = constants.RadiusEarth
        mu1 = constants.MuEarth
        mu2 = 4.0 * mu1
        period1 = 2.0 * np.pi * np.sqrt(radius**3 / mu1)
        period2 = 2.0 * np.pi * np.sqrt(radius**3 / mu2)
        self.assertAlmostEqual(period2 / period1, 0.5)

    def test_orbital_frequency_scales_with_square_root_mu(self):
        """Verify orbital frequency scales as sqrt(mu/r^3)."""
        radius = constants.RadiusEarth
        mu1 = constants.MuEarth
        mu2 = 4.0 * mu1
        frequency1 = np.sqrt(mu1 / radius**3)
        frequency2 = np.sqrt(mu2 / radius**3)
        self.assertAlmostEqual(frequency2 / frequency1, 2.0)

    def test_orbital_period_frequency_product(self):
        """Verify the Keplerian period-frequency relationship."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        period = 2.0 * np.pi * np.sqrt(frame.lstar**3 / frame.P1mu)
        frequency = np.sqrt(frame.P1mu / frame.lstar**3)
        self.assertAlmostEqual(period * frequency, 2.0 * np.pi)


# ============================================================================
# Circular-orbit velocity regression tests
# ============================================================================

class TwoBodyFrameVelocityTests(unittest.TestCase):
    """Verify circular-orbit velocity relationships."""

    def test_circular_velocity_scales_inverse_square_root_with_radius(self):
        """Verify circular velocity scales as r^(-1/2)."""
        mu = constants.MuEarth
        radius1 = constants.RadiusEarth
        radius2 = 2.0 * radius1
        velocity1 = np.sqrt(mu / radius1)
        velocity2 = np.sqrt(mu / radius2)
        self.assertAlmostEqual(velocity2 / velocity1, 1.0 / np.sqrt(2.0))

    def test_circular_velocity_scales_square_root_with_mu(self):
        """Verify circular velocity scales as sqrt(mu)."""
        radius = constants.RadiusEarth
        mu1 = constants.MuEarth
        mu2 = 4.0 * mu1
        velocity1 = np.sqrt(mu1 / radius)
        velocity2 = np.sqrt(mu2 / radius)
        self.assertAlmostEqual(velocity2 / velocity1, 2.0)

    def test_escape_velocity_squared_is_twice_circular_velocity_squared(self):
        """Verify v_escape^2 = 2*v_circular^2."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        circular_velocity = np.sqrt(frame.P1mu / frame.lstar)
        escape_velocity = np.sqrt(2.0 * frame.P1mu / frame.lstar)
        self.assertAlmostEqual(escape_velocity**2 / circular_velocity**2, 2.0)

    def test_characteristic_velocity_squared_equals_mu_over_length(self):
        """Verify v*^2 = mu/l*."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertAlmostEqual(frame.vstar**2, frame.P1mu / frame.lstar)


# ============================================================================
# General scaling invariance tests
# ============================================================================

class TwoBodyFrameInvariantTests(unittest.TestCase):
    """Verify nondimensional relationships are independent of physical scale."""

    def test_multiple_physical_scales_have_same_nondimensional_velocity(self):
        """Verify v*/sqrt(mu/l*) equals one for several physical systems."""
        cases = ((constants.MuEarth, constants.RadiusEarth), (constants.MuSun, constants.AU), (4.0 * constants.MuEarth, 2.0 * constants.RadiusEarth), (25.0 * constants.MuEarth, 9.0 * constants.RadiusEarth))

        for mu, radius in cases:
            frame = TwoBodyFrame(mu, radius)
            expected_velocity = np.sqrt(mu / radius)
            self.assertAlmostEqual(frame.vstar / expected_velocity, 1.0)

    def test_multiple_physical_scales_have_same_nondimensional_time(self):
        """Verify t*/sqrt(l*^3/mu) equals one for several physical systems."""
        cases = ((constants.MuEarth, constants.RadiusEarth), (constants.MuSun, constants.AU), (4.0 * constants.MuEarth, 2.0 * constants.RadiusEarth), (25.0 * constants.MuEarth, 9.0 * constants.RadiusEarth))

        for mu, radius in cases:
            frame = TwoBodyFrame(mu, radius)
            expected_time = np.sqrt(radius**3 / mu)
            self.assertAlmostEqual(frame.tstar / expected_time, 1.0)

    def test_multiple_physical_scales_have_same_nondimensional_acceleration(self):
        """Verify a*/(mu/l*^2) equals one for several physical systems."""
        cases = ((constants.MuEarth, constants.RadiusEarth), (constants.MuSun, constants.AU), (4.0 * constants.MuEarth, 2.0 * constants.RadiusEarth), (25.0 * constants.MuEarth, 9.0 * constants.RadiusEarth))

        for mu, radius in cases:
            frame = TwoBodyFrame(mu, radius)
            expected_acceleration = mu / radius**2
            self.assertAlmostEqual(frame.astar / expected_acceleration, 1.0)

    def test_nondimensional_escape_speed_is_sqrt_two(self):
        """Verify escape speed is sqrt(2) in characteristic velocity units."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        escape_velocity = np.sqrt(2.0 * frame.P1mu / frame.lstar)
        self.assertAlmostEqual(escape_velocity / frame.vstar, np.sqrt(2.0))

    def test_nondimensional_gravity_is_one(self):
        """Verify gravity at the characteristic radius is one in acceleration units."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        gravity = frame.P1mu / frame.lstar**2
        self.assertAlmostEqual(gravity / frame.astar, 1.0)

    def test_nondimensional_circular_period_is_two_pi(self):
        """Verify the circular period at l* is 2*pi in characteristic time units."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        period = 2.0 * np.pi * np.sqrt(frame.lstar**3 / frame.P1mu)
        self.assertAlmostEqual(period / frame.tstar, 2.0 * np.pi)


# ============================================================================
# Cross-system consistency tests
# ============================================================================

class TwoBodyFrameCrossSystemTests(unittest.TestCase):
    """Compare characteristic scaling between Earth-centered and Sun-centered systems."""

    def test_earth_and_sun_velocity_scales_are_physically_reasonable(self):
        """Verify Earth and Sun characteristic velocity scales have expected magnitudes."""
        earth_frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        sun_frame = TwoBodyFrame(constants.MuSun, constants.AU)
        self.assertGreater(earth_frame.vstar, 7000.0)
        self.assertLess(earth_frame.vstar, 9000.0)
        self.assertGreater(sun_frame.vstar, 29_000.0)
        self.assertLess(sun_frame.vstar, 31_000.0)

    def test_earth_characteristic_period_is_physically_reasonable(self):
        """Verify the Earth-radius characteristic period has the expected magnitude."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        period_seconds = 2.0 * np.pi * frame.tstar
        self.assertGreater(period_seconds, 5000.0)
        self.assertLess(period_seconds, 6000.0)

    def test_earth_surface_gravity_scale_is_physically_reasonable(self):
        """Verify the Earth characteristic acceleration is near surface gravity."""
        frame = TwoBodyFrame(constants.MuEarth, constants.RadiusEarth)
        self.assertGreater(frame.astar, 9.0)
        self.assertLess(frame.astar, 10.0)

if __name__ == "__main__":
    unittest.main()