name: Build wheels

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13, macos-14]
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - uses: pypa/cibuildwheel@v2.17.0
        with:
          output-dir: wheelhouse
        env:
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*
          CIBW_SKIP: "pp*"
          CIBW_BEFORE_ALL_LINUX: |
            apt update
            apt install -y clang-13 cmake
            cd /tmp
            wget -q https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
            apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
            echo "deb https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
            apt update
            apt install -y intel-oneapi-mkl-devel intel-oneapi-openmp
            source /opt/intel/oneapi/setvars.sh
          CIBW_BEFORE_ALL_MACOS: |
            brew install llvm cmake
            python -m pip install mkl-devel
          CIBW_BEFORE_ALL_WINDOWS: |
            choco install -y llvm cmake
            pip install mkl-devel
      
      - uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
