name: pip-ubuntu-22

on:
  workflow_dispatch:

  schedule:
    - cron: "0 20 * * 5"
  #push:
  #  branches:
  #    - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]
        python-version: ["3.9"]
        compiler: ["clang-13"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ubuntu dependencies
        env:
          COMPILER: ${{ matrix.compiler }}
        run: bash $GITHUB_WORKSPACE/.github/install_ubuntu_dependencies.sh

      - name: Add python requirements
        run: python -m pip install --upgrade wheel setuptools && python -m pip install -r requirements.txt

      - name: Build and install
        run: pip install --verbose .
      - name: Run CMake on Docs  # Now that library is installed on runner, we can properly doc the pyd
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DPIP_INSTALL=True -DBUILD_SPHINX_DOCS=True
      - name: Build Sphinx Docs 
        run: cmake --build build --target sphinx --config Release -- -j1 
      - name: Deploy Sphinx Docs 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/doc/sphinx # The folder the action will deploy to gh-pages
