name: pip-ubuntu-20

on:
  schedule:
    - cron: "0 20 * * 5"
  push:
    branches:
      - gcc-build-fix

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]
        python-version: ["3.9"]
        compiler: ["gcc-10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ubuntu dependencies
        env:
          COMPILER: ${{ matrix.compiler }}
        run: bash $GITHUB_WORKSPACE/.github/install_ubuntu_dependencies.sh

      - name: Add python requirements
        run: python -m pip install --upgrade wheel setuptools && python -m pip install -r requirements.txt

      - name: Build and install
        run: pip install --verbose .
